/* The Road to Apologetics — 200 questions across 20 themed chapters.
   Each question, once its prepared answer is opened, earns a badge. Questions
   are sent to the backend as-is; Claude answers in the user's language. */
var APOLO_THEMES = [
  { theme: "Does God Exist?", icon: "🌌", questions: [
    "What are the strongest reasons to believe God exists?",
    "Doesn't the universe having a beginning point to a Creator?",
    "Why is the fine-tuning of the universe evidence for God?",
    "Where does objective morality come from if not from God?",
    "Can something really come from nothing without a cause?",
    "Doesn't human consciousness point to something beyond matter?",
    "Is the design we see in nature real evidence, or only apparent?",
    "If God exists, why does he seem hidden?",
    "Who created God? Doesn't that just push the question back a step?",
    "Is believing in God irrational in a scientific age?"
  ]},
  { theme: "Can I Trust the Bible?", icon: "📜", questions: [
    "How do we know the Bible hasn't been changed over the centuries?",
    "Aren't there thousands of contradictions in the Bible?",
    "How were the books of the Bible chosen (the canon)?",
    "Can we trust the New Testament manuscripts we have?",
    "Weren't the Gospels written long after Jesus by non-eyewitnesses?",
    "Does archaeology support or undermine the Bible?",
    "How reliable is the Old Testament next to other ancient texts?",
    "Why are there four Gospels that don't perfectly match?",
    "Were the Gospels copied from earlier pagan myths?",
    "How do we know the right books weren't left out?"
  ]},
  { theme: "Who Is Jesus?", icon: "✝", questions: [
    "Did Jesus actually exist as a historical figure?",
    "Did Jesus claim to be God, or did the church invent that later?",
    "Was Jesus just a good moral teacher?",
    "How can Jesus be both fully God and fully man?",
    "Could the disciples have simply made up the story of Jesus?",
    "What did Jesus mean by 'Son of Man' and 'Son of God'?",
    "Were Jesus' miracles real, or legends that grew over time?",
    "Why did Jesus have to die?",
    "How is Jesus different from other religious founders?",
    "Did Jesus fulfill the Messianic prophecies?"
  ]},
  { theme: "The Resurrection", icon: "🌅", questions: [
    "What is the historical evidence that Jesus rose from the dead?",
    "Couldn't the resurrection just be a later legend?",
    "What are the 'minimal facts' most historians accept?",
    "Could the disciples have stolen the body?",
    "Did the witnesses simply hallucinate the risen Jesus?",
    "Was Jesus really dead, or did he only faint (the swoon theory)?",
    "Why is the empty tomb significant?",
    "Why would the disciples die for something they knew was false?",
    "How did the resurrection turn frightened followers into bold martyrs?",
    "Why does the resurrection matter for me today?"
  ]},
  { theme: "Evil & Suffering", icon: "🕯️", questions: [
    "If God is good and all-powerful, why is there evil?",
    "Why does God allow innocent children to suffer?",
    "Is suffering evidence that God doesn't exist?",
    "What's the difference between moral and natural evil?",
    "Why doesn't God just stop all evil right now?",
    "How does free will help explain the existence of evil?",
    "Can any real good come out of suffering?",
    "How does the cross speak to human suffering?",
    "Why does God allow natural disasters?",
    "How can I trust God when I'm in deep pain?"
  ]},
  { theme: "Faith & Reason", icon: "🧭", questions: [
    "Isn't faith just believing without evidence?",
    "What does the Bible actually mean by 'faith'?",
    "Can faith and reason really work together?",
    "Isn't it arrogant to be certain about God?",
    "Why do intelligent people disagree about God?",
    "Is it okay to have doubts as a Christian?",
    "Doesn't blind faith lead to dangerous extremism?",
    "How is trusting God like trusting a person?",
    "Can you prove God exists like a math equation?",
    "What role does evidence play in Christian belief?"
  ]},
  { theme: "Science & Faith", icon: "🔬", questions: [
    "Doesn't science make God unnecessary?",
    "Are science and Christianity really at war?",
    "Doesn't evolution disprove the Bible?",
    "How old is the universe, and does it matter for faith?",
    "Weren't many founders of modern science Christians?",
    "Can a serious scientist believe in miracles?",
    "Does the Big Bang support or challenge belief in God?",
    "How should we read Genesis and the days of creation?",
    "Doesn't neuroscience show the soul is just the brain?",
    "Is intelligent design science or religion?"
  ]},
  { theme: "World Religions", icon: "🕊️", questions: [
    "Aren't all religions basically the same?",
    "How can one religion claim to be the only true one?",
    "Isn't it intolerant to say other beliefs are wrong?",
    "What about sincere people in other faiths?",
    "Aren't all paths just climbing the same mountain?",
    "How is Christianity different from other religions at its core?",
    "Doesn't your religion just depend on where you were born?",
    "Can other religions contain any truth at all?",
    "Why would a loving God allow so many religions?",
    "Isn't claiming exclusive truth just a power play?"
  ]},
  { theme: "Morality & Ethics", icon: "⚖️", questions: [
    "Can a person be good without God?",
    "Where do human rights actually come from?",
    "If morality comes from God, is it just arbitrary?",
    "Isn't morality only an evolved survival instinct?",
    "Who are you to say anything is really wrong?",
    "Doesn't the Bible endorse slavery and genocide?",
    "How do Christians decide what is right and wrong?",
    "Is morality simply relative to culture?",
    "Why do humans have a conscience at all?",
    "What makes humans more valuable than animals?"
  ]},
  { theme: "Prophecy Fulfilled", icon: "📖", questions: [
    "What prophecies did Jesus actually fulfill?",
    "Aren't 'fulfilled' prophecies just written after the fact?",
    "How specific are the Messianic prophecies like Isaiah 53?",
    "What about Daniel's prophecy of the timing of the Messiah?",
    "Do any Bible prophecies predict later world events?",
    "How do we know prophecies weren't simply self-fulfilled?",
    "What are the odds of one person fulfilling many prophecies?",
    "Does the survival of Israel fulfill prophecy?",
    "What did the prophets say about the nations coming to God?",
    "How does fulfilled prophecy build confidence in Scripture?"
  ]},
  { theme: "The Nature of God", icon: "🔥", questions: [
    "How can God be three persons and yet one God?",
    "Where is the Trinity taught in the Bible?",
    "Isn't the Trinity a plain contradiction?",
    "Did the church just invent the Trinity at Nicaea?",
    "Is the Holy Spirit a person or an impersonal force?",
    "How did Jesus relate to the Father as God?",
    "Do Christians actually worship three gods?",
    "What does 'begotten, not made' mean?",
    "Can we use analogies for the Trinity without error?",
    "Why does the Trinity matter for love and relationship?"
  ]},
  { theme: "Miracles", icon: "✨", questions: [
    "Are miracles even possible in principle?",
    "Isn't there always a natural explanation eventually?",
    "Did Hume actually disprove miracles?",
    "Why don't we see biblical-scale miracles today?",
    "How can we tell a real miracle from a coincidence?",
    "Do answered prayers count as evidence?",
    "What about miracle claims in other religions?",
    "Is the resurrection the best-attested miracle in history?",
    "Doesn't modern science rule out the supernatural?",
    "Can a rational modern person believe in miracles?"
  ]},
  { theme: "Church & History", icon: "⛪", questions: [
    "Hasn't Christianity caused endless wars and violence?",
    "What about the Crusades and the Inquisition?",
    "Why are so many Christians hypocrites?",
    "Didn't the church oppose science, as with Galileo?",
    "Hasn't religion mostly held back human progress?",
    "What good has Christianity actually done in history?",
    "Why are there so many different denominations?",
    "How should Christians respond to church scandals and abuse?",
    "Do I need the church, or can I just believe on my own?",
    "How do we face the church's real failures honestly?"
  ]},
  { theme: "Heaven, Hell & Judgment", icon: "🌤️", questions: [
    "What happens to us after we die?",
    "How could a loving God send anyone to hell?",
    "Isn't eternal punishment unjust for finite sins?",
    "What is heaven actually going to be like?",
    "Is hell literal fire, or separation from God?",
    "What about people who never heard about Jesus?",
    "Won't a good God simply accept everyone in the end?",
    "How can heaven be happy if loved ones are missing?",
    "Why is there a final judgment at all?",
    "How can I have assurance of eternal life?"
  ]},
  { theme: "Hard Bible Passages", icon: "📕", questions: [
    "Why does God command violence in the Old Testament?",
    "Does the Bible really condone slavery?",
    "How should we read the Old Testament laws today?",
    "What do we do with the harsh 'cursing' Psalms?",
    "Why did God test Abraham by asking for Isaac?",
    "How do we handle apparent contradictions in Scripture?",
    "Why are there so many strange rules in Leviticus?",
    "What about the treatment of women in the Bible?",
    "How do the Old and New Testaments fit together?",
    "How do I read a hard passage in its proper context?"
  ]},
  { theme: "Origins & the Cosmos", icon: "🌠", questions: [
    "How did the universe itself begin?",
    "Where did the first life come from?",
    "Does the fine-tuning of physics point to design?",
    "Are we alone in the universe, and would it matter?",
    "Why is there something rather than nothing?",
    "Can a 'multiverse' explain away the appearance of design?",
    "What does being 'made in God's image' mean?",
    "How do Christians think about the age of the earth?",
    "Is there real purpose in the cosmos, or only randomness?",
    "Does human uniqueness point to a Creator?"
  ]},
  { theme: "Objections from Culture", icon: "🏛️", questions: [
    "Isn't Christianity anti-science and backward?",
    "Why does the church seem so focused on sexuality?",
    "What does the Bible teach about same-sex relationships, explained with love?",
    "Isn't the Bible sexist and patriarchal?",
    "How can you push your morality on other people?",
    "Isn't religion just a crutch for the weak?",
    "Why should ancient texts guide modern life?",
    "Isn't faith a private matter that shouldn't go public?",
    "How do Christians love people they deeply disagree with?",
    "Isn't tolerance the highest virtue of all?"
  ]},
  { theme: "Other Scriptures & Cults", icon: "📗", questions: [
    "How is the Bible different from the Quran?",
    "What do Christians say about Islam's view of Jesus?",
    "How does Mormonism differ from historic Christianity?",
    "What about the Jehovah's Witnesses' teaching on Jesus?",
    "Isn't the Book of Mormon just another testament of Jesus?",
    "How do I lovingly respond to someone in a cult?",
    "What makes a group a 'cult' in theological terms?",
    "What about Eastern ideas like reincarnation and karma?",
    "How does the New Age view of God differ from Christianity?",
    "Why do Christians reject scriptures added after the Bible?"
  ]},
  { theme: "Doubt & Deconstruction", icon: "🌫️", questions: [
    "Is it okay to honestly doubt my faith?",
    "I feel like God is silent — is he even there?",
    "I was hurt by the church; why should I stay?",
    "What if I only believe because of how I was raised?",
    "How do I deal with prayers that go unanswered?",
    "Everyone around me is deconstructing — am I crazy to still believe?",
    "What if I don't 'feel' God anymore?",
    "How do I rebuild my faith after serious doubt?",
    "Can I be honest with God about my anger and confusion?",
    "Where do I take my very hardest questions?"
  ]},
  { theme: "Sharing Your Faith", icon: "💬", questions: [
    "How do I share my faith without being pushy?",
    "What's the simplest way to explain the gospel?",
    "How do I answer a question when I don't know the answer?",
    "How do I talk with a skeptical friend?",
    "What do I do if someone mocks or gets angry?",
    "How do I share with family without creating tension?",
    "What's the role of my own story and testimony?",
    "How do I actually invite someone to follow Jesus?",
    "How do I keep loving someone who keeps saying no?",
    "How do I point to Jesus in everyday conversations?"
  ]}
];
